@echo Uninstalling GBGMC files
@pause
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\HVT_AR_BLACK.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\HVT_AR_WDLND.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\HVT_CQB_BLACK.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\HVT_CQB_WDLND.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\HVT_SNP_BLACK.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\HVT_SNP_WDLND.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\HVT_STG_BLACK.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\HVT_STG_WDLND.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_AR.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_AR_BLACK.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_AR_WDLND.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_CQB.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_CQB_BLACK.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_CQB_WDLND.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_HVT_AR.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_HVT_CQB.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_HVT_SNP.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_HVT_STG.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_SNP.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_SNP_BLACK.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_SNP_WDLND.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_STG.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_STG_BLACK.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi\SO_STG_WDLND.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\AK-Guy.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\HVT_AR.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\HVT_CQB.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\HVT_HDG.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\HVT_SNP.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\HVT_STG.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\SO_AR.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\SO_CQB.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\SO_SNP.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\SO_STG.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\STD_AR.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\STD_CQB.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\STD_SNP.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas\STD_STG.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Civ1.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Civ2.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Civ3.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Civ4.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Civ5.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Civ6.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Civ7.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Civ8.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\HVT_AR1.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\HVT_AR2.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Param_AR1.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_AR1.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_AR2.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_AR3.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_AR4.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_AR5.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_AR6.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_AR7.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_AR8.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_HDG1.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_HDG2.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_HDG3.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_HDG4.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_HDG5.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_HDG6.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_HDG7.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_HDG8.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SMG1.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SMG2.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SMG3.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SMG4.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SMG5.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SMG6.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SMG7.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SMG8.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SNP1.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SNP2.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SNP3.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SNP4.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SNP5.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SNP6.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SNP7.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_SNP8.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_STG1.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_STG2.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_STG3.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_STG4.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_STG5.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_STG6.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_STG7.kit
del GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos\Tango_STG8.kit
del GroundBranch\Content\GroundBranch\DefaultLoadouts\BreakOut.kit
del GroundBranch\Content\GroundBranch\DefaultLoadouts\NoTeamCamouflage.kit
del GroundBranch\Content\GroundBranch\GameMode\AssetExtraction.lua
del GroundBranch\Content\GroundBranch\GameMode\AssetExtractionSemiPermissive.lua
del GroundBranch\Content\GroundBranch\GameMode\AssetExtractionSemiPermissiveValidate.lua
del GroundBranch\Content\GroundBranch\GameMode\AssetExtractionValidate.lua
del GroundBranch\Content\GroundBranch\GameMode\BreakOut.lua
del GroundBranch\Content\GroundBranch\GameMode\BreakThrough.lua
del GroundBranch\Content\GroundBranch\GameMode\KillConfirmed.lua
del GroundBranch\Content\GroundBranch\GameMode\KillConfirmedSemiPermissive.lua
del GroundBranch\Content\GroundBranch\GameMode\SecurityDetail.lua
del GroundBranch\Content\GroundBranch\GameMode\SecurityDetailSemiPermissive.lua
del GroundBranch\Content\GroundBranch\GameMode\SecurityDetailSemiPermissiveValidate.lua
del GroundBranch\Content\GroundBranch\GameMode\SecurityDetailValidate.lua
del GroundBranch\Content\GroundBranch\Lua\AssetExtraction.lua
del GroundBranch\Content\GroundBranch\Lua\AssetExtractionSemiPermissive.lua
del GroundBranch\Content\GroundBranch\Lua\BreakOut.lua
del GroundBranch\Content\GroundBranch\Lua\BreakThrough.lua
del GroundBranch\Content\GroundBranch\Lua\Common\Actors.lua
del GroundBranch\Content\GroundBranch\Lua\Common\Codenames.lua
del GroundBranch\Content\GroundBranch\Lua\Common\Items.lua
del GroundBranch\Content\GroundBranch\Lua\Common\Logger.lua
del GroundBranch\Content\GroundBranch\Lua\Common\Maths.lua
del GroundBranch\Content\GroundBranch\Lua\Common\Strings.lua
del GroundBranch\Content\GroundBranch\Lua\Common\Tables.lua
del GroundBranch\Content\GroundBranch\Lua\Common\Validator.lua
del GroundBranch\Content\GroundBranch\Lua\Common\Vectors.lua
del GroundBranch\Content\GroundBranch\Lua\KillConfirmed.lua
del GroundBranch\Content\GroundBranch\Lua\KillConfirmedSemiPermissive.lua
del GroundBranch\Content\GroundBranch\Lua\Objectives\AvoidFatality.lua
del GroundBranch\Content\GroundBranch\Lua\Objectives\ConfirmKill.lua
del GroundBranch\Content\GroundBranch\Lua\Objectives\Exfiltrate.lua
del GroundBranch\Content\GroundBranch\Lua\Objectives\NoSoftFail.lua
del GroundBranch\Content\GroundBranch\Lua\Players\RespawnLaptop.lua
del GroundBranch\Content\GroundBranch\Lua\Players\Teams.lua
del GroundBranch\Content\GroundBranch\Lua\SecurityDetail.lua
del GroundBranch\Content\GroundBranch\Lua\SecurityDetailSemiPermissive.lua
del GroundBranch\Content\GroundBranch\Lua\Spawns\Common.lua
del GroundBranch\Content\GroundBranch\Lua\Spawns\Groups.lua
del GroundBranch\Content\GroundBranch\Lua\Spawns\Priority.lua
del GroundBranch\Content\GroundBranch\Lua\Spawns\Random.lua
del GroundBranch\Content\GroundBranch\Mission\747\KillConfirmed.mis
del GroundBranch\Content\GroundBranch\Mission\Arena\KillConfirmed.mis
del GroundBranch\Content\GroundBranch\Mission\City\BreakOut.mis
del GroundBranch\Content\GroundBranch\Mission\City\BreakThrough.mis
del GroundBranch\Content\GroundBranch\Mission\City\KillConfirmed.mis
del GroundBranch\Content\GroundBranch\Mission\Compound\KillConfirmed.mis
del GroundBranch\Content\GroundBranch\Mission\Compound\KillConfirmed_AceOfSpades.mis
del GroundBranch\Content\GroundBranch\Mission\Creek\KillConfirmed.mis
del GroundBranch\Content\GroundBranch\Mission\RunDown\BreakOut.mis
del GroundBranch\Content\GroundBranch\Mission\RunDown\KillConfirmed.mis
del GroundBranch\Content\GroundBranch\Mission\SmallTown\AssetExtraction.mis
del GroundBranch\Content\GroundBranch\Mission\SmallTown\AssetExtractionSemiPermissive.mis
del GroundBranch\Content\GroundBranch\Mission\SmallTown\KillConfirmed.mis
del GroundBranch\Content\GroundBranch\Mission\SmallTown\KillConfirmedSemiPermissive.mis
del GroundBranch\Content\GroundBranch\Mission\SmallTown\SecurityDetail.mis
del GroundBranch\Content\GroundBranch\Mission\SmallTown\SecurityDetailSemiPermissive.mis
del GroundBranch\Content\GroundBranch\Mission\Tanker\BreakOut.mis
del GroundBranch\Content\GroundBranch\Mission\Tanker\KillConfirmed.mis
del GroundBranch\Content\Localization\GroundBranch\en\AssetExtraction.csv
del GroundBranch\Content\Localization\GroundBranch\en\BreakOut.csv
del GroundBranch\Content\Localization\GroundBranch\en\BreakThrough.csv
del GroundBranch\Content\Localization\GroundBranch\en\KillConfirmed.csv
del GroundBranch\Content\Localization\GroundBranch\en\SecurityDetail.csv
rd .\GroundBranch\Content\GroundBranch\Lua\Common
rd .\GroundBranch\Content\GroundBranch\Lua\Objectives
rd .\GroundBranch\Content\GroundBranch\Lua\Players
rd .\GroundBranch\Content\GroundBranch\Lua\Spawns
rd .\GroundBranch\Content\GroundBranch\AI\Loadouts\EurAsi
rd .\GroundBranch\Content\GroundBranch\AI\Loadouts\MidEas
rd .\GroundBranch\Content\GroundBranch\AI\Loadouts\Narcos
@echo Done.
@pause
